version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://node:4000/auth
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
  node:
    build: .
    command: "npm run dev"
    ports: 
      - "4000:4000"
    #tty: true
    working_dir: /usr/app
    volumes:
      - ./src/:/usr/app/src/
      - ./package.json:/usr/app/package.json
      - ./tsconfig.json:/usr/app/tsconfig.json
    environment: 
      PORT: 4000
    depends_on:
      - graphql-engine
      - postgres
